com:
  prhythm:
    ssjv001:
      kafka:
        exchange:
          enabled: true
          bootstrapAddress: localhost:9092
spring:
  jackson:
    serialization:
      write-self-references-as-null: true
    default-property-inclusion: non_null
